### ISSUE TITLE
Generate image - API call error: 502 Server Error: Bad Gateway for url

### ISSUE THREAD

**Issue by pdas-cp4i** [aws-solutions-library-samples/guidance-for-virtual-personal-stylist-on-aws#3]
Getting this error while testing Generate Image.

API call error: 502 Server Error: Bad Gateway for url: https://cwfvg17xa6.execute-api.us-east-1.amazonaws.com/dev/image?query=Stylish+anarkali+suit+or+gown+made+of+lightweight%2C+breathable+fabrics+like+rayon%2C+modal+or+cotton

![Capto_Annotation](https://github.com/user-attachments/assets/18ba3562-8d7c-48e4-8069-b0b78899e782)

{
    "requestId": "56a1e9e1-2457-4505-8334-f3600bf4d7b8",
    "ip": "35.175.139.217",
    "user": "-",
    "requestTime": "10/Nov/2024:02:19:34 +0000",
    "httpMethod": "GET",
    "resourcePath": "/image",
    "status": "502",
    "protocol": "HTTP/1.1",
    "responseLength": "36"
}

**Comment by skwatra1992** [comment]
Please check into model access for SDXL which is generating the output image by invoking lambda function. Also please attach the logs for lambda when invoking the image model.

**Comment by pdas-cp4i** [comment]
Thanks for the quick response.
Yes. Model access for SDXL 1.0 is enabled. But,  anthropic.claude-3-haiku-20240307-v1:0 was not enabled.  This step was missing in the requirements instructions.  
It looks good now.


![Capto_Annotation](https://github.com/user-attachments/assets/c0d2c51b-37fa-4699-ae10-52453bb2241a)
